apiVersion: v1
kind: Service
metadata:
  name: hello-world-service-py
spec:
  selector:
    app: hello-world-api-py
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
