name: Deploy to Minikube

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Start minikube
        uses: medyagh/setup-minikube@master
       

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: hshanka/hello-world-api-py:latest

      - name: Deploy to Minikube
        run: |
          minikube start
          minikube kubectl -- apply -f deployment.yaml
          minikube kubectl -- apply -f service.yaml
