name: Deploy to Minikube

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Start minikube
        uses: medyagh/setup-minikube@master
      
     
      - name: Build image
        run: |
          export SHELL=/bin/bash
          eval $(minikube -p minikube docker-env)
          docker build -f ./Dockerfile -t local/example .
          echo -n "verifying images:"
          docker images        

      - name: Deploy to Minikube
        run: |
          minikube start
          minikube kubectl -- apply -f deployment.yaml
          minikube kubectl -- apply -f service.yaml
